### ISSUE TITLE
Implement at() in terms of operator[] to avoid bound checks in deque and vector

### ISSUE THREAD

**Issue by fgallegosalido** [stotko/stdgpu#184]
The containers in the STL that support random access implement two different functions to access specific elements in the container:

- `operator[]`
- `at`

`operator[]` just accesses the element without bound checks, while `at` perfoms the same operation, but doing bound checks and throwing an out_of_bounds exception when the index is out of bounds.

I propose that the containers (deque and vector basically) implement `at()` in terms of `operator[]`, and perfom bound checks only when calling `at()`. That way they're more compliant to the STL ones. This is my proposed solution for vector (for deque is the same idea):

```
template <typename T>
inline STDGPU_DEVICE_ONLY typename vector<T>::reference
vector<T>::at(const vector<T>::index_type n)
{
    return const_cast<vector<T>::reference>(static_cast<const vector<T>*>(this)->at(n));
}


template <typename T>
inline STDGPU_DEVICE_ONLY typename vector<T>::const_reference
vector<T>::at(const vector<T>::index_type n) const
{
    STDGPU_EXPECTS(0 <= n);
    STDGPU_EXPECTS(n < size());
    STDGPU_EXPECTS(occupied(n));

    return this->operator[](n);
}


template <typename T>
inline STDGPU_DEVICE_ONLY typename vector<T>::reference
vector<T>::operator[](const vector<T>::index_type n)
{
    return _data[n];
}


template <typename T>
inline STDGPU_DEVICE_ONLY typename vector<T>::const_reference
vector<T>::operator[](const vector<T>::index_type n) const
{
    return _data[n];
}
```

**Comment by stotko** [comment]
Thanks for the report! Defining the functions this way is definitely the better solution. Exception handling goes beyond this particular case and probably needs to be investigated separately.

**Comment by stotko** [comment]
I opened #185 to make the suggested changes. Unfortunately, the CI is currently broken, so merging will be delayed until the problem gets fixed.

**Comment by fgallegosalido** [comment]
Throwing `std::out_of_bounds` is the way the STL reports the error, but this is code executed in the GPU, so error handling doesn't have to be compliant to the STL containers, in my opinion.

Also, I suspected that CI was going to break due to the fact that now `operator[]` doesn't do bounds check, so a deeper look in the test must be done.

**Comment by stotko** [comment]
CI breakage is actually unrelated to the changes as installing the required packages already fails:

https://dev.azure.com/patrickstotko/stdgpu/_build/results?buildId=409&view=logs&j=26ef8efa-a13f-5927-0bd6-f52d59ca1b8a&t=6e8fff25-1341-5e4b-5d44-a0c41a8a32ee&l=74

```
Reading package lists...
E: Failed to fetch http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/InRelease  403  Forbidden [IP: 195.135.221.134 80]
E: The repository 'http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease' is no longer signed.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://storage.googleapis.com/bazel-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>

##[error]Bash exited with code '100'.
```

We need to wait until the CI images get either reverted or fixed.

**Comment by stotko** [comment]
CI is working again. Merged the PR as all tests passed. Thanks again for the report!
