### ISSUE TITLE
Cannot include stdgpu to an existing OpenMP/HIP project

### ISSUE THREAD

**Issue by alephpiece** [stotko/stdgpu#186]
I'm working on an OpenMP/HIP code and trying to include stdgpu as a subproject. What I need is to

- compile stdgpu with hipcc/hcc,
- compile my HIP sources with hipcc/hcc,
- compile the rest with gcc/clang, and
- leave all the linking things to gcc/clang

It seems like stdgpu needs to pass `-DCMAKE_CXX_COMPILER=hcc` to cmake to build HIP backend but hcc doesn't support `-fopenmp` yet. So the OpenMP libraries are missing when a `find_package(OpenMP)` is encountered. Is there any way to workaround this?

I've tried to set the compiler to clang. The compiler complains that `-hc` is an unknown argument. It looks like this is an hcc argument required by the  `rocthrust::rocthrust` target.

```console
clang++  -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_HIP -Dstdgpu_EXPORTS
...
-isystem /opt/rocm-3.3.0/hip/include -isystem /opt/rocm/include  -stdlib=libc++ -O3 -DNDEBUG -fPIC   -hc -fPIC -std=c++14 -o CMakeFiles/stdgpu.dir/impl/iterator.cpp.o -c /external/stdgpu/src/stdgpu/impl/iterator.cpp
clang-9: error: unknown argument: '-hc'
```

**Comment by stotko** [comment]
It should work when setting the C++ compiler to hcc. Have you properly set the backend to HIP? 

You can do this
- either by passing `-DSTDGPU_BACKEND=STDGPU_BACKEND_HIP` to CMake when building stdgpu,
- or `set(STDGPU_BACKEND ${STDGPU_BACKEND_HIP} CACHE STRING "")` before `add_sudirectory(stdgpu)` if you embedded it.

During CMake configuration, it should print a summary which contains a line mentioning the chosen backend. That should be `STDGPU_BACKEND_HIP` if configured correctly in your case.

OpenMP is not used by the HIP backend, so `find_package(OpenMP)` will not be called by stdgpu. If you need to use the HIP backend and also use OpenMP at the same time in your code, you may try hip-clang instead and see whether this works.

**Comment by alephpiece** [comment]
Thanks.
The cmake flag for HIP backend was set properly in my previous post. Eventually, I get around this by adding include directories manually using `target_include_directories` other than using cmake targets.
The configuration file `hip-config.cmake` (ROCm 3.3 with HCC) provides several targets required by `rocthrust::rocthrust` and `rocprim::rocprim_hip`. On my system, the include directories taken by these targets are always set to the default ROCm installation path under `/opt/rocm`. Once I removed `find_package(hip)` and these targets, everything was fine.

**Comment by stotko** [comment]
Thanks for the detailed description of your problem.

It looks like that you have multiple versions of ROCm installed, i.e. `/opt/rocm-3.3`, `/opt/rocm-3.x`, etc., and the one you would like to use is not the one the default path `/opt/rocm` points to. Is that correct?

You are right that stdgpu chooses the targets and include directories in the default path `/opt/rocm`. The related lookups are [here](https://github.com/stotko/stdgpu/blob/master/cmake/hip/Findthrust.cmake). We could improve our module to only let it search in the user-provided path to ROCm (via variables like `HIP_PATH`) for the targets and the HCC/HIP-Clang compiler and to fall back to the default path if HIP could not be found there. I will take a look at this.

**Comment by alephpiece** [comment]
Yes. There are multiple ROCm installations managed by my administrator. I think it's quite usual for cluster users.

**Comment by alephpiece** [comment]
I can only test the installation on ROCm 3.3 with HCC & GCC since I don't have many platforms or compilers at hand.

FYI, I take [this](https://github.com/alephpiece/rocThrust-examples/blob/main/cmake/SetupHIP.cmake) simple configuration to find HIP and rocThrust.

**Comment by stotko** [comment]
Thanks for the pointer. That's exactly the direction I had in mind. We could also try to set the correct compiler effectively simulating CMake's compiler detection to a certain degree. This way, the user would only need to set the path to ROCm to select the corresponding compiler, includes, and targets.

You may have already noticed that we bumped the minimum ROCm version to 3.5 (see #188) since HCC has been deprecated for a long time and is removed in more recent versions like ROCm 3.8. Instead, out HIP backend now relies on HIP-Clang which seems to be in a much better shape and does not need the workarounds for HCC.

**Comment by alephpiece** [comment]
That's great. I'll take this update and move on to hip-clang as long as ROCm 3.5+ is available on my system.

**Comment by stotko** [comment]
The `ROCM_PATH` regular and environment variables are now honored to select the desired ROCm installation. Simulating the compiler detection is a bit more complicated. I guess you have to explicitly set the compiler in your project anyways, so maybe this change is sufficient. Let me know if this solves your problem or we have to improve further.

**Comment by alephpiece** [comment]
Yes, it is sufficient. I think this is closed.
