### ISSUE TITLE
error: redefinition of ‘constexpr const bool stdgpu::numeric_limits<T>::is_specialized’

### ISSUE THREAD

**Issue by geotyper** [stotko/stdgpu#243]
Ubuntu 20
Cuda 11.4

Library compiled by CUDA back-end successfully, examples work.
But when add STDGPU  to small project, next error during compiling:

/usr/local/include/stdgpu/impl/limits_detail.h:73:42: error: redefinition of ‘constexpr const bool stdgpu::numeric_limits<T>::is_specialized’
![image](https://user-images.githubusercontent.com/30755433/124385583-fcf99e80-dcde-11eb-8305-557440d3d7b7.png)
![image](https://user-images.githubusercontent.com/30755433/124385592-0b47ba80-dcdf-11eb-809e-0ea286c6b7d4.png)

**Comment by stotko** [comment]
Does this error also occur with different host compilers (GCC, Clang) and different CUDA versions (11.3, etc.)? Furthermore, is this the only error you are getting? Or are there also errors regarding the `is_signed`, `is_integer`, etc. member variables? If possible, could you attach a (minimal) reproducable example?

**Comment by geotyper** [comment]
Try only GCC and CUDA 11.4, this is my work setup. 
Have 5 errors, as list  of this variables:
  ```
  /**
     * \brief Whether the type is signed
     */
    static constexpr bool is_signed = false;
    /**
     * \brief Whether the type is an integer
     */
    static constexpr bool is_integer = true;
    /**
     * \brief Whether the type is exact
     */
    static constexpr bool is_exact = true;
    /**
     * \brief Number of radix digits
     */
    static constexpr int digits = 1;
    /**
     * \brief Integer base
     */
    static constexpr int radix = 2;
```
Add only #include header from expamle vector.cu
#include <iostream>
#include <thrust/copy.h>
#include <thrust/reduce.h>
#include <thrust/sequence.h>

#include <stdgpu/memory.h>          // createDeviceArray, destroyDeviceArray
#include <stdgpu/iterator.h>        // device_begin, device_end
#include <stdgpu/platform.h>        // STDGPU_HOST_DEVICE
#include <stdgpu/vector.cuh>        // stdgpu::vector

and

**Comment by geotyper** [comment]
![image](https://user-images.githubusercontent.com/30755433/124396542-de14ff80-dd12-11eb-9b9a-48058c577121.png)

this errors if add include_directory with headers

**Comment by stotko** [comment]
> if add include_directory with path to include directory of stdgpu, errors more than 200

Could you elaborate what you exactly mean by that? The lines
```
find_package(stdgpu REQUIRED)
target_link_libraries(${EXECUTABLE_NAME} PUBLIC stdgpu::stdgpu)
```
are sufficient to add all necessary properties `stdgpu` needs to your project, including the include directory paths.

It seems like this is an error/incompatibility in your project. `stdgpu` requires compilation with C++14 and should enforce this by its imported `cxx_std_14` property. Did you set the C++ standard somewhere in your project? Could you provide more details on your project? In particular, the build configuration, i.e. the `CMakeLists.txt` file(s), would be helpful to know (if it is possible for you to attach them).

**Comment by geotyper** [comment]
Made small project to solve problem, under some changes in cmakelists.txt all work as expected:
```
cmake_minimum_required(VERSION 3.5)

if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
  set(CMAKE_CUDA_ARCHITECTURES 61)
  message(CMAKE_CUDA_ARCHITECTURES)
endif()

project(CellInstancing LANGUAGES CUDA CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CUDA_STANDARD 14)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_SEPARABLE_COMPILATION ON)


set(EXECUTABLE_NAME "CUDA_exp")

find_package(CUDA REQUIRED)


SET(TARGET_H
)

SET(TARGET_SRC
main.cu
)

SET(TARGET_CUDA_H
cuda_exp.cuh
)

SET(TARGET_CUDA_SRC
cuda_exp.cu
)

find_package(stdgpu REQUIRED)

set(Cuda_common_include "/usr/local/cuda/samples/common/inc")
include_directories(${Cuda_common_include})

message(${CUDA_INCLUDE_DIRS})
include_directories(${CUDA_INCLUDE_DIRS})

add_executable(${EXECUTABLE_NAME} ${TARGET_SRC} ${TARGET_H} ${TARGET_CUDA_H} ${TARGET_CUDA_SRC} )

set_target_properties(${EXECUTABLE_NAME} PROPERTIES CUDA_ARCHITECTURES "61")
target_link_libraries(${EXECUTABLE_NAME} ${CUDA_LIBRARIES})
target_link_libraries(${EXECUTABLE_NAME} stdgpu::stdgpu)
```
