### ISSUE TITLE
Findthrust.cmake parse error

### ISSUE THREAD

**Issue by HWZen** [stotko/stdgpu#407]
**Describe the bug**
Cannot config project because [Findthrust.cmake@15](https://github.com/stotko/stdgpu/blob/master/cmake/Findthrust.cmake#L15) cannot find the thrust properly.

Look at this code:
``` cmake
string(REGEX REPLACE "#define THRUST_VERSION[ \t]+" "" THRUST_VERSION_STRING ${THRUST_VERSION_STRING})
```
It does not take into account that #define THRUST_VERSION may be followed by comments.

Unfortunately, cuda 12.4's thrust/version.h has a comment after THRUST_VERSION
``` c++
/*! \def THRUST_VERSION
 *  \brief The preprocessor macro \p THRUST_VERSION encodes the version
 *         number of the Thrust library as MMMmmmpp.
 *
 *  \note THRUST_VERSION is formatted as `MMMmmmpp`, which differs from `CCCL_VERSION` that uses `MMMmmmppp`.
 *
 *         <tt>THRUST_VERSION % 100</tt> is the sub-minor version.
 *         <tt>THRUST_VERSION / 100 % 1000</tt> is the minor version.
 *         <tt>THRUST_VERSION / 100000</tt> is the major version.
 */
#define THRUST_VERSION 200301 // macro expansion with ## requires this to be a single value
```

So `${THRUST_VERSION_STRING} `in cmake was parsed to `200301 // macro expansion with ## requires this to be a single value` and led to subsequent errors in judgment.

If you think what I'm saying makes sense, I'll be happy to fix it.

**System (please complete the following information):**
 - OS: Windows 11
 - Compiler: Visual Studio 2022
 - Backend: CUDA 12.4
 - Library version: main branch

**Comment by stotko** [comment]
Thanks for the report. This indeed looks like a bug in `Findthrust.cmake`  and your explanation makes perfect sense. A PR to fix this issue would be very welcome.
