### ISSUE TITLE
Please help to answer the two questions about this, thank you

### ISSUE THREAD

**Issue by wangshuxihe00** [stotko/stdgpu#413]
1.When I want to use other containers (e.g., list, array), do I need to implement one myself?
2.The hip version of the example does not have the use of container classes, is it supported?

**Comment by wangshuxihe00** [comment]
Are you saying that ordered versions of maps/sets cannot maintain their characteristics when executed in parallel on gpu, so they are difficult to implement?

**Comment by stotko** [comment]
Not exactly. Implementing the characteristic that a map/set remains sorted within a kernel after a thread inserted/erased a value - while at the same time other threads are attempting to also do so with different values - is challenging, especially as these operations should be as fast as possible. Here, a lot of things have to be considered in terms of synchronization. I believe that this is definitely possible. But given that the unordered version is often sufficient and also faster for many applications, the ordered version received less attention and has not been implemented yet.

**Comment by wangshuxihe00** [comment]
I see. Thank you

**Comment by stotko** [comment]
Closing this issue as the questions have been answered. If there are further issues, feel free to ask again.
