### ISSUE TITLE
Docs on size parameters

### ISSUE THREAD

**Issue by david-tingdahl-nvidia** [stotko/stdgpu#418]
**Is your feature request related to a problem? Please describe.**
Thanks for an awesome library! I have a question/suggestion on a doc update to clarify how capacity, max_size and bucket_count are defined. 

I'm using max_load_factor=1 and my interpretation is as follows:

* capacity:  Requested number of buckets. 
* bucket_count: capacity rounded up to the nearest power-of-two.
* max_size: Unclear. seems to be an arbitrary number in between capacity and bucket count.

When I calculate the current load factor, should I use "size/bucket_count" or "size/max_size"? 

**Describe the solution you'd like**
Updated docs to better describe these variables

**Comment by stotko** [comment]
For calculating the current load factor, you can use `size() / bucket_count()` or alternatively directly call `load_factor()` which does the same thing. This matches the [respective definition](https://en.cppreference.com/w/cpp/container/unordered_map/load_factor) in the C++ standard library.

Concerning the meaning of the different functions, you are right about `capacity` and `bucket_count`. `max_size` denotes the total number of elements the container can hold which is `bucket_count` + `excess_count` (implementation detail, i.e. an extra space allocated to handle collisions). So `max_size` > `bucket_count` >= `capacity`.

**Comment by david-tingdahl-nvidia** [comment]
Thanks for the clarifications!
